spring:
  datasource:
    url: "jdbc:mysql://localhost:8889/account"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"

useUnicode: "true&characterEncoding=UTF-8"
